name: ublox_gnss
description: Driver for the u-blox M* GNSS receivers.
dependencies:
  gnss_location:
    url: github.com/toitware/toit-gnss-location
    version: ^1.1.0
  location:
    url: github.com/toitware/toit-location
    version: ^1.0.0
  ubx_message:
    url: github.com/toitware/ubx-message
    version: ^2.1.2
