dependencies:
  gnss_location:
    url: github.com/toitware/toit-gnss-location
    version: ^1.0.1
  location:
    url: github.com/toitware/toit-location
    version: ^1.0.0
  ubx_message:
    url: github.com/toitware/ubx-message
    version: ^2.1.0
